"""empty message

Revision ID: 3b24417ce2ac
Revises: 71aaa70067d4
Create Date: 2022-06-30 18:29:30.330130

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3b24417ce2ac'
down_revision = '71aaa70067d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('content', sa.Text(), nullable=False))
    op.drop_column('post', 'konten')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('konten', mysql.VARCHAR(length=250), nullable=False))
    op.drop_column('post', 'content')
    # ### end Alembic commands ###
