"""empty message

Revision ID: 71aaa70067d4
Revises: 01cea6a6ea03
Create Date: 2022-06-30 18:28:12.781824

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '71aaa70067d4'
down_revision = '01cea6a6ea03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('konten', sa.String(length=250), nullable=False))
    op.drop_column('post', 'content')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('content', mysql.VARCHAR(length=13), nullable=False))
    op.drop_column('post', 'konten')
    # ### end Alembic commands ###
